name: ServiceNow GitHub Actions Demo

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    # Purpose of this job is to Apply Remote Changes for the branch triggering 
    # the pipeline build to the Dev instance, then publish the application to 
    # app repo using the template versioning format. 
    name: Publish from Dev
    runs-on: ubuntu-latest
    # Below line can be used to set conditionals for modifying your pipeline as needed.
    # if: ${{ github.event_name == 'pull_request'}}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: curl
        run: curl -X GET ${{ secrets.SN_DEV_INSTANCE }}

      - name: ServiceNow CI/CD Apply Changes
        uses: ServiceNow/sncicd-apply-changes@2.0.0
        env:
          nowUsername: 'admin'
          nowPassword: 'n#>iec;6w2XFT3<9;2*h_drZ9]D?=05c+=7'
          nowSourceInstance: 'https://dev271975.service-now.com'
          appSysID: '3c3fc36383124a106edfe3e0deaad330'
